apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: delay-pod-network-by-names
spec:
  experiments:
  - scope: pod
    target: network
    action: delay
    desc: "delay pod network by names"
    matchers:
    - name: names
      value:
      - "ts-cancel-service-77948bfdc6-qdnx6"
    - name: namespace
      value:
      - "default"
    - name: interface
      value: ["eth0"]
    - name: time
      value: ["200"]
    - name: timeout
      value: ["300"]