apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: loss-pod-network-by-names
spec:
  experiments:
  - scope: pod
    target: network
    action: loss
    desc: "loss pod network by names"
    matchers:
    - name: names
      value:
      - "ts-notification-service-79957fb84f-zzt7q"
    - name: namespace
      value:
      - "default"
    - name: interface
      value: ["eth0"]
    - name: percent
      value: ["60"]
    - name: timeout
      value: ["300"]