apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: remove-container-by-names
spec:
  experiments:
  - scope: container
    target: container
    action: remove
    desc: "remove container by names"
    matchers:
    - name: container-names
      value: ["ts-admin-user-service"]
      # pod name
    - name: names
      value: ["ts-admin-user-service-65c86cff75-6tzz7"]
    - name: namespace
      value: ["default"]
    #- name: evict-count
    #  value: ["2"]